### PR TITLE
encountering an error when trying to load localhost:3000. Will include screenshot.

### PR DESCRIPTION
**Pull request by CatalystCoder**
screen shot 2016-03-22 at 5 02 23 pm

I'm not sure what this error means or how to go about fixing it. I followed along with the rails video but I'm not sure what to do. Sorry if this is a terrible question. I expected it to show me the home page.

### CODE REVIEW

**Comment by CatalystCoder** [comment]
Error has changed after I changed some code. Pushing up again.

**Comment by CatalystCoder** [comment]
screen shot 2016-03-22 at 5 10 06 pm

**Comment by StevenThiesfeld** [comment]
A class name should never have underscores, always use camelcase (MainPagesController)

**Comment by CatalystCoder** [comment]
Changed the 'devise' in MainPages Controller to 'home' and this is what I get.
screen shot 2016-03-22 at 5 49 59 pm

**Pull request merged**
