### PR TITLE
setting up step creation for tutorials  Issue #42

### PR DESCRIPTION
**Pull request by maedae**

### CODE REVIEW

**Comment by maedae** [comment]
Hey! Having some issues with a specific error during the Step instance creation. I'm a little perplexed because I haven't actually encountered this, and have used the same basic forms_for setup in my other create pages for Tutorials and Chapters without issues. 

**Here is the error I'm getting:**
screen shot 2016-03-24 at 10 56 06 am

**Here is the terminal output:**
screen shot 2016-03-24 at 10 56 25 am

**Here is the code for my step creation view page**
`<h1>New Step</h1>
Chapter:  <%= @chapter.title %><br>
Tutorial: <%= @tutorial.title %><br><br>

<%= form_for  @new_step, :url => "create/confirmation" do |f| %>
  Title: <%= f.text_field :title %><br />
  Draft: <%= f.check_box :draft %><br />
  Warning: <%= f.check_box :warning %><br />
  Description:<br /> <%= f.text_area :description %><br />
  Video Start Time: <%= f.text_field :start_time %><br />
  Video End Time: <%= f.text_field :end_time%><br />
  <%= f.submit %>
<% end %>
`

**Here are my controller actions:**
class StepsController < ApplicationController

  def create
    @tutorial = Tutorial.find_by_id(params[:tutorial_id])
    @chapter = Chapter.find_by_id(params[:chapter_id])
    @new_step = Step.new
    render "create"
  end

  def create_confirmation
    @tutorial = Tutorial.find_by_id(params[:tutorial_id])
    @chapter = Chapter.find_by_id(params[:chapter_id])
    @new_step = Step.new(:title => params[:step][:title], :description => params[:step][:description], :draft => params[:step][:draft], :warning =>[:step][:warning], :start_time => (params[:step][:start_time]).to_i, :end_time => (params[:step][:end_time]).to_i :chapter_id => @chapter.id)
    @new_step.save
    render "/"
  end
end

**Comment by maedae** [comment]
NOTE:

I pushed my code, too. I really don't care for how github deals with code snippets. 
GitHub < Slack

**Comment by halfghaninne** [comment]
Hm. Based on the error, I would try putting a `binding.pry` in StepsController#create_confirmation above line 13 and check out what the values of the params you are trying to access are. Looks like there is some issue with how you are trying to reference them.

**Comment by maedae** [comment]
binding.pry isn't working for me in rails.

**Comment by halfghaninne** [comment]
Do you have pry in your Gemfile?

**Comment by maedae** [comment]
Issue #43 completed in branch -- can add description to steps

**Comment by maedae** [comment]
Issue #44 completed in branch -- user can set step as a warning or standard step

**Pull request merged**
